addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.5.5")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"  % "0.14.3")
addSbtPlugin("com.github.sbt" % "sbt-dynver"    % "5.1.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.3.2-M1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.12.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "2.3.1")
